export const ADD_TASK_START = 'ADD_TASK';
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS'
export const ADD_TASK_FAILED = 'ADD_TASK_FAILED'

export const REMOVE_TASK_START = 'REMOVE_TASK_START';
export const REMOVE_TASK_SUCCESS = 'REMOVE_TASK_SUCCESS';
export const REMOVE_TASK_FAILED = 'REMOVE_TASK_FAILED';


export const UPDATE_TASK_START = 'UPDATE_TASK_START';
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';
export const UPDATE_TASK_FAILED = 'UPDATE_TASK_FAILED';

export const RETRIEVED_TASKS = 'RETRIEVED_TASKS';

export const SUBSCRIBE_TASKS_SUCCESS = 'SUBSCRIBE_TASKS_SUCCESS';
export const SUBSCRIBE_TASKS = 'SUBSCRIBE_TASKS';

export const UNSUBSCRIBE_TASKS = 'UNSUBSCRIBE_TASKS';
export const UNSUBSCRIBE_TASKS_SUCCESS = 'UNSUBSCRIBE_TASKS_SUCCESS';