export const ADD_MESSAGE_START = 'ADD_MESSAGE';
export const ADD_MESSAGE_SUCCESS = 'ADD_MESSAGE_SUCCESS'
export const ADD_MESSAGE_FAILED = 'ADD_MESSAGE_FAILED'

export const REMOVE_MESSAGE_START = 'REMOVE_MESSAGE_START';
export const REMOVE_MESSAGE_SUCCESS = 'REMOVE_MESSAGE_SUCCESS';
export const REMOVE_MESSAGE_FAILED = 'REMOVE_MESSAGE_FAILED';


export const UPDATE_MESSAGE_START = 'UPDATE_MESSAGE_START';
export const UPDATE_MESSAGE_SUCCESS = 'UPDATE_MESSAGE_SUCCESS';
export const UPDATE_MESSAGE_FAILED = 'UPDATE_MESSAGE_FAILED';

export const FETCH_MESSAGES_FAILED = 'FETCH_MESSAGES_FAILED';
export const FETCH_MESSAGES_START = 'FETCH_MESSAGES_START';
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';

export const SUBSCRIBE_MESSAGES_SUCCESS = 'SUBSCRIBE_MESSAGES_SUCCESS';
export const RETRIEVED_MESSAGES = 'RETRIEVED_MESSAGES';
export const SUBSCRIBE_MESSAGES = 'SUBSCRIBE_MESSAGES';