//export const ADD_TASK_START = 'ADD_TASK';


export const REQUEST_ACCOUNTS = 'REQUEST_ACCOUNTS';
export const RETRIEVED_ACCOUNTS_SUCCESS = 'RETRIEVED_ACCOUNTS_SUCCESS';
export const RETRIEVED_ACCOUNTS_FAILED = 'RETRIEVED_ACCOUNTS_FAILED';

export const REQUEST_WEBPROPERTIES = 'REQUEST_WEBPROPERTIES';
export const RETRIEVED_WEBPROPERTIES_SUCCESS = 'RETRIEVED_WEBPROPERTIES_SUCCESS';
export const RETRIEVED_WEBPROPERTIES_FAILED ='RETRIEVED_WEBPROPERTIES_FAILED';

export const REQUEST_PROFILES = 'REQUEST_PROFILES';
export const RETRIEVED_PROFILES_SUCCESS = 'RETRIEVED_PROFILES_SUCCESS';
export const RETRIEVED_PROFILES_FAILED = 'RETRIEVED_PROFILES_FAILED';


export const REQUEST_DATA = 'REQUEST_DATA';
export const RETRIEVED_DATA_SUCCESS = 'RETRIEVED_DATA_SUCCESS';
export const RETRIEVED_DATA_FAILED = 'RETRIEVED_DATA_FAILED';



